run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - unused
    - gofmt
    - govet
    - misspell
    - nakedret
    - unconvert
    - paralleltest
  disable:
    - errcheck
    - gosec
    - gosimple
    - ineffassign
    - noctx
    - staticcheck

linters-settings:
  errcheck:
    exclude-functions: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
      - paralleltest
      text: "does not use range value in test Run"
  exclude-dirs:
    - test-cmds
