name: lint

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [main, master]
  pull_request:
    branches: '**'
  merge_group:
    types: [checks_requested]


jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          skip-save-cache: true



  govulncheck:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: govulncheck
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - id: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          go-version-file: './go.mod'
          check-latest: true
          go-package: ./...
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: false
      - name: install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
      - name: actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          actionlint -color


  # This job is here as a github status check -- it allows us to move
  # the merge dependency from being on all the jobs to this single
  # one.
  lint_mergeable:
    runs-on: ubuntu-latest
    steps:
      - run: true
    needs:
      - golangci
      - govulncheck
      - actionlint
